---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-first-secret
  namespace: prod
spec:
  encryptedData:
    password: AgADvAeIGNrXEg9o1rr7bJUcewqolPIaqZM5gDLkvOl6wEjdNxLXxmM/cttnshEwz6B0PXt/l4fFNn8ISykUAVYrU/TkexlIoIuya1Qv6JvipMhMEEboyPKcwpmXu/gHdmkQl728zy0OmB5SQIikXcLa2rRUW8dsO5GQsikqct0bXjyUV/t8P+IKyHxbGMztQU0DOv6G8GpJ/FUUiLSHPUOZYQm/sKzcn1mPZFrr5mvp2e+mz/VSgFM0786M+Dj34cnAi9hKFYF7p++sQx5X1p0i53raarVQLugFjBLWfoypVqckrSFW2KzGrNzIlDHMbrb08X7Ps4A6ilS8RXzMm9Q5AQ23MkEfLnE4izLM3QZq4FpLAB1dImG8vqF+cIoq2ngfqL52NsCV6D8LK5AEW7JofoR7MnpOE7mYDIKmFxfr4oRmMVeNO8e7oHAM541J49KD9fIoVVIXbhT992mqjRO1ZXhZOWAID1HhgGDsH1yPM0j0t61yjdaUtlEc431xhnYATvrAcXtesCS761Rkh6ecPC3Zo7OjT8LOWS6HU1OITW3gscRAeTl2PYf+EoeY+3gFSA6+bAxVrkHuGSh35BXJgYGU5Rvly2QRptWSxpXEc5ozyssesC5HLd6pF8I+LpuDv45YDefAWHUuPvJNsKn+UkwzW3AEDoE/QFP9M8v39vaMWbzRs6b05PZ0dSn2CMkleMgE4C9dumkxwT6hqSkrVMcJ
    username: AgBQOw0dV0VlyjTKTVzacaLcbpLVU4ApLOeCtEhcbhPo8WUdmiAn87QuTIQcW431T3VvPH42dfONTz7YLJZeHqMGQ+p+kZ4CekMhH4Wvj+PnQASByW9kneRrFPxNiiTm6+Pvn734chbkw3VjERUfvwgXhdD7qu1Dy+uXk/TtWMLqBVIMR6uWR1reBouKsv6jCvKVBS7HD52YS0O3enW1zLMCk8t3nnQ1ewvXxpvZ1NSlp5C8uJQz1uYSKj4XYlk26739eKOU/hHXazKAM1kFvt+D1CXIooJYLQLj6HtU0NAbRoPlki2I5JkqecXN6Xnps1JqaA/l9okQ5n4tBa9CIkixMdwFGQWesXp1gyPluGTdEYB4anjzPZaRXgcwmAIkVijlqsvokaM/cB0PLHzkMBFleFZtcnFr3vQ6H23n6T8OWN6/yWwY3bZfo3qil9Q2L6pI0FQLfKxVdLcExLL8FUH0bHHBE6KS1T41PukARpxwoerbd9z9VxnR/IO5AzpyV5oqgEHbkD/UWCiHibRjnXPwJ/F3QDysS4/wjcqKSaRusGLOC5RbmeJQ4MKV9XLEWEUoQrKOfXLTkbTTKFvNkIBDr86UpxDXeTRhEySo16fVHz3xDOamXti7COgeAxH+6K7V19e4EWAhfc5itGXfH4I6JLqRh3r2NamoKxTHwNdiorfXemj4m3yXN3S1wv8piVfaTHijg1p4vQ==
  template:
    metadata:
      name: my-first-secret
      namespace: prod
    type: Opaque
