---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-prod-secret
  namespace: prod
spec:
  encryptedData:
    password: AgBHlg05Q1re3Qyu9NtbILCjwiho+V2nGjpkM6RRnsfRn8fSfzqSamOoaiPzhL1Hc3o4Ff2SYVVjEOdiTkAZU2w4QRH/ftPA9ptXf9URzR4vq0TAjOcbd6fbXu7p6OalQ0aNlzAXGstycQL06upQjRN2iD5kUbkLQO4gv2H8j24BEjWrgOxXIwALp6ctYibYsY8UoPvobLQLZnv0rxnOy6YnXUH9L3kWZpJaNDulXmPEyPp1SytrypLt0sgkZuokEnU5X+K/FmRT1rSY4oqkhSpVBHbNohhl1iRArQpiuTs3ho+J5G0ld2lEXOAErUndqHCS40DtmJpC7GEV1CNb7MY3PuFWl33sPCGt+m3MURjGEGgI2DdGp+jNoLysH0Tv/5+3DfQxlwwhLmn6zBCm2DRrOi3DVQzaiQsun4eErebXzseRoZZ+xDYBA7WPTbjWddU+m+Tf4P3sWME+FuiGWmfURNFDqLFi5Bb+L38DoeP+TIQQRgbQEVXq7V4CkCwzHlGSSH1fPvO8b4+nQ5gnFLT6A2l5rQjKOq4rc90vgKqMaNjOdBaxT9SHmYWR5Rfq4X3LZ8fWd3cjqA2pKnzKqSHbYHBnXDW8JuEC9/Rrvb4nlpRvxmbZ6mVzsOgcCBPeEiGT9Me1kjidTbDv2fZevk7p9VO6dKya/1s4dWGRhRjJ1yKyLRW0hvgsKKU4LNjGhZVJBceW0EKWqcIXispmph8oiM6GIoW++Q==
    username: AgCbnXvpT+AhhZE7sJZjkouZJoChMOawZSde9sMBK9tFI4Kl/qCeBuJbpzpC9RcCL9oQ2biylWPiktdCmsts21BykJg1xIemuNuuEPX/UizYLeA8Cm/sSn9IXkqjmUeX0fTMiSQgQaolNWkznTUgLl19r94SAPvT+GEtL7NIsaAQf9+z51///aGtVI0beZLTb5JZDD352HZbzUbvXFImdrafuGM+4TlRNvaYFndQwRI/d/dNgv7/iGuDoX4iCO9qhKxir229rn/OtRqrKts2L1ClE474CLCecwqUFSw8fZvbB2eDYx/uOmjJUdgKe/jz3KxqwU0vR6sLO1pSCJ+3j7hn47qT7bwClfoita/fz2+48f4VQ9H9R0xZSWIJ8iLslr1yxiPSh+j76qINFHmAFKuxh+KUTZ6CAqZYqMrDp9O00x0k/+eZR5ktFwEHwMpCYzUB42+nwo3E6lDrXCRZns+1DrhUuOIO0od0FJwOCySONM2KKUQjFjhWB8Gv3FgcqbsC3MeXppUmH4mO9X6aVlbMuAbUiJBzu08qQzQSc+EWWKKKlE+vd3gMwE0j5ZK+RvIqOvHlKffbdAOqLmev5mmT92j3Vam1M9capEwbVetb1PvuLhYoPmSPbsaCFbq9f+Lj10wgePaSQFAJTPuUS5lTy5Zuq+vNKIEnxJsfNOdSgkDFRg7TZ7eAgS6VGyZ9shCKIetB4TvJzw==
  template:
    metadata:
      name: my-prod-secret
      namespace: prod
