---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-first-secret
  namespace: prod
spec:
  encryptedData:
    password: AgBOeaOCL+RfMDUkLvzkBNUUwJsS9z+lNVrZVSwXJqImTeUKGrLl9OOsJfFp2Tiy5Vqt4yk+QNNXryQzOcPOpNFoVP9nd6Seijbgnw5uM2dnnq/Gtr5QGHcfcBrGhMtzfkGwXXLXxYjTdu0TO42znXxl9iTt/d5LvCEzSD8LZhkjpPHw7NL9D9y5Bg8sWWt1FagXfPpY5BG37oWKNVx42hKPLDonMwHHrPih/hjYuMqcF8hj6ec/lnShY3583d16cwj/ExtQZLTMXnUzlDxWFsMEQ8Vw0OrFWgu/n6dCkIbB40uZPe1RTzFo3QqnsAMDB//0RTkex8QaiQb3zpw3mw8bXdNS8q2bnDj3HcZoQPLYWlZIaL/Ol4oNCLpQlsVknvwu1DbblX8oCWlwyb0BXCmIeJ5m1mERHASMr/CUAVyiR9OOcNpx0cEGMU9vnWtAUW89/jnBZetE5M/lVxs6YyML9bOnYu1cl6SKBNBkpaFRbDcBy4NX/nhtksU5JC5TtRhzUSOM1VUFe1eXwACU82JztTH6Z6dv+9pX+UHrvlKRJasBe7GKXKtL4zjSpB3x/S7VsiUTlbf7cdHB3J1rTzdI1xMn0jzpse04AVuo5gaJtymBhr3ts6h7HKSkl6ZtJXZnDNai0JenpzbIfGktdSbUVT6a4Oo6BRawD5LWMxsjZ/emreuy2q+qli1LuZxZZxkNX1bWXPDd2z9kMFTQiueIKhrYJlQ/iw==
    username: AgC+ij4EsR0OhXVCVurQsR0kjMnKZ+dQXelTXMvK5kgMf3hb5ezGftQGlSZa4xBgpxSr5yb4RA6J0cOiHdSf2hqxYebfkVFh0MtmePO5LREq2eTr07EEBJXpUuj7Js0p4W090vzs+GEu0DQCwgqQhk7khLqXXCqx+LXZAFgROfC8m4BIVJj9aUVUZaorShqVVjn/aF6HiZBfeixkwRQQOKpHscosW0pxJwrV3/DOPRGg4ALAd/+yEy7eNbZ26xCrArgf5GoEAGgkkfzB3+5sJ5gR/zVjw9IGLDuTMfAEwkD7+7VjQiNq8gkJLtFT2AlxE/Y6jjPyGqgbWs/m4lZ8/vSvXE363df3ImrhC1d5L1w6JaYuI8RrwBjIDquyy9d0ZuxsZVWlRbPV5kxm8Q4hlsZ1rAOdRSj52r6//UuiiW/4U9sF9C5CGbcGZVfCfmJ2histm4cx7BfbG48srmFfkp8/jr9ZjueYu5TU/VhWeRnXN1qKdmo7w1mppfJf9paVZS0lCvgI6aayaJeE87Nh/J/yfKLpGPBMpvGlSxEVHkq3ZpOWF5TSxSIvXro28+T2o1EvZ60Cv95kuF/xeJWtIHz47KkT7V86ViRRKfy9tLe8MGUpzsFj79iU2q+OGSFl0c7AJPcQuxP4z/nxXyzVR4on7YT81LdOT/sz/Ut4F2VNzPmOOK9TUButXUYRKIqVjms4ly99ZNsN+g==
  template:
    metadata:
      name: my-first-secret
      namespace: prod
