---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-first-secret
  namespace: default
spec:
  encryptedData:
    password: AgBC9XNsdso2IRM4ipQAeFKolwRUHTTK1CC0Vu8+sE7xEhFn69gCzKYvpaDEiODPA4mQVCtUg1MHwoQJ4UIflsFPYWeTS2T5XSe8tKp6C3Uq3mTAGH+N33/cVvbX4BkHkeKiFvzNkKoYQXZ3kmkRqtqxv/0H060gGwme+bgY/FEmPMXV/PtF/L5zh5mC2eKZdKzzI7+HyIbI6gCGkzEJ85VA24ywnAUOKPYYWwMrxxqHFH9Y1XmM1LlL09ZC7lqxbcSWybYgZggKkisS6ps5PC0yKMOmrYU9v/Dgl9/Ue7/24mtsF6fXKn8IeI68GTW+btpPKuaKnMZcfepnhB+Y/hmZRkBhibd4UZX+UmtmE3EBqToxvokwSDp3/QFZMSYmFbTq2WWmMp9cnAiepfFTz1PYMixeoa4ij+TlMRgG1LvNLCP8CDMwD3X0RH6j0LwWIgDrHJUfAGCc3FKiAQ1aRPkxO8CFu2ur2j82IozaJcWF/DlXiSikCGAGPbiZ2eSl+BjZmahmWypJIJUJzYHXeQFFjgHgALNs9vX4ULV6poudb1MFRKIFcve08MI2yG8ZL96hGlHlEh3lzNrA7KHfIofeOxGYdX7gdwtch3VWpAVHFO4uiaUgdHb5bwPWOlt289r4OuG1368rMOhOxkmWPsWhXPBUVZwzD/1kxsEfROaoPffXEHzw4AOUiWjTFZI5is8FfxEKlRhPhjoCLNanMbCxMcclC9a/6w==
    username: AgBdAYiLJjh8crJZJuLsSV1ofBEjpilOaAGVdddKtJhfgY745PigLHs9MPnNEZG6vAhdGH5OWzIozitvPvatRYrc2hS/LTJMCp9ryHQry4C/dv9XmeImiLoTZAmCGxHIldD7AvNMI98mVS9DVb/W263Cyj+hM8mPi+nVQjZg5QVTAhxMYyrqkytlj1keDuRujxpB2Bc+wzG4Osm32kSEjIni/ZMTsywoWCkcm5SUhiG1Y5jMBSjAxQQPIOtKQDFpSYYPO8yuNjldpqNJtHIXtMSmR2Q+ADIywTUY3mXv8PmtRrqlm7G75q5fncBssIZUGnW+NZ38hUHUEj3lArz7RlaiyyjpbpQl6Nje8kIMQOr/kOjjfkY1WTros1BlEZddTsKJp3fls43N7/lAKcs14+U+rY1KFWCBC22Hby5Sj7OsWXQmZM4+KhKImuzAeLkeVT3bzF58BC57Wd4rt00GJMelntr0va3BUpZgbvCy7ftE1JMpWCwYJXu+XnBSqzNA6Tkw3mVhVdOb5Kc8dl1+j6z2k/oeYln4wZWJKR2scUuJIjVpwBORjobss6stZXArRFUKQ+CUPHyGGZ3ZwW4m1advelMSf8hX1G5PLK+pj9Eosq1i3Vy8NQdCogVvrHHLN16JOtreKxEHGbewVyLoQsH/nxpi99iEig8E76ZThCAON/ZgjdYC2eCabVAYw3vKMsrdD1RRMt3MXA==
  template:
    metadata:
      name: my-first-secret
      namespace: default
