---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-first-secret
  namespace: default
spec:
  encryptedData:
    password: AgA+R9CpfCfNQfLEzEkVarQzDFcXYbYiRRApWMkGXCM+T73LRa9gIowQHX80MsSasxE5H2o0qK9KTqcTHe4xIdp26RrTwmMotPvWcXzZDCeYI7IxZD4A0omMlLr6Nn+2VdhEQlmbR9wpwMSOr1XFQtpFr3TnbW7wCZtj2HyflKrhFgEqOzh6s0m+8mz7yxjEnRCfW01NhKizSrI/2i6FvXcFO081uu5c7lyCF4FTEdVt85j0WxQCIe48rLfarNHeH8zxfZoE6mHxMBvpPPRm6Qu570RYSOQjWEc7o44jYcJvfdoqIVulR4BDBW4gtHG3+zV7310ojoR2jUZEBsYXkxZyn40eoDYI/1gJSEpz7VXh7/k9jh+QPkUZxAM6i3pGUyZbo3X9jPXqbIq1QYvrhQ8FdjA68Urc03qcHeqhk7BSpGCIZFsbNfDnKH0MX/Z9IeXdBrJ/uMOsP0DueeGod3pvlJS5lXxnfB06NkJxZq0AT4jylJwOW1/P3HgF1u+TYFmrCJo07jkAOSAwTtMjGQikWLqj6L3VbVDoPUpaUKM9ogWXd6G6D41Ny7w/b8OeF2QYzPmELIVP2zaNmTtMoUhRmbdi3NQkxc61WnP/5f2CJvWQDs3nQS95yJIw5TDjYyWtnfFrOOZX9wYxsaaT/JOrzYAsI2iClKrr9Vo4M2deP4P7zJKbD6wAzisK/1SBQpHXJVjhKBPZEX9Vp8GK/CPrG+Mh
    username: AgBayzvjyVf4DAkK/V6cYq7vt5tjX6llTgERvFV9wlObAXAVNQVq5It5wR6LkvmcRuJiBgqjzsfKINdtrPW1Gc1XhrGSFmBmpKor9cW1SREwW6PCcoQC7dlUmS8kQlAd7BMraFAghhtE47vl4m/1f5qlyYz2/RZY3tagHFZFXqdnfw9cREoQZ7Eg6zsiI9RWITIGRHT0u576l0Cu+vMhErdx3ySTdg5Fv0PjwF3uKLsZA/QuNauT+7R7z0qp2KZiLaVmt/2Ldi3Zlw2UazmJtFKGJbGDH5+M0rxOKfYNoAnseSuhFH8otd3e5USBDhoXWBv9HKrgjV0QGh+QdqUgqvsN0oqn+XYJ8oB8A5TT06p4bAokKAmVEI0yFVNkAkvEYHRJmj4dhw5iea6d0aYUqDB/HklFaZBF8pFOPuN+CW6+XUe7iQFKGxy01pzGDPxIUMh8w0TxTp4FlmFLZK+tOrsvRY6IaOeQoS98d2FRxa4TxNE2D0wBFRAGZHcqhyBHQFhmGIUQqCAIAEdjFhskI0+EMI6hK2G4oF4dcbj2HBJqVwnThn2POfDzJUSyFeolcgqZXkiBv4aot5E6LPANYzHYZuescVDp1E2DBnb2LhYqQ2CIzD9Nbs4me/PEXFMnhskA+00zdd8wkMoZ6hIuK5skYBpKGhd0DY1wV7b41POkjtKZA1IfNjwBg2Ba44Gs5pSlTLkV3bpIGQ==
  template:
    metadata:
      name: my-first-secret
      namespace: default
