---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: guestbook-db-pass
  namespace: default
spec:
  encryptedData:
    password: AgAcrEvwuFl/TN8moJ2i7B/3T9xcVLt1o4R5cN8JCQ2ZpNxi/gzMzCVzP2BMLtZDqoJxeCTa8nyIpmxwI1wWwmBDCm1ngacDCws133IhF/jAE56EzBcvJv2VgimxSWo8AGTcP5qLOuV6cJjQ5TWWi4NrYFit02ExW5GA8P7r15IPxJGhYX63e2VYwcR9rz6+h2sYovZGwy9mGOOo7jzJUrpqskQKiELLNyzlYB4FqG438XP8NOzG2Lu8yzvDRJ+2RP7tfnB9qGBiTR9OeR8RzDsm93OBLK0uYDUg8f4ZpGrhi7sa51RCguadvEeCVJqKWPBsWwFY2PxFuZuFibGRFHV6JN5v9OdCt2aFQ6qEJgXvFbaaCQR9TUzPvoLVExeMESBubqWE5L20IGSDQ04/B9+j4Oy3sxgslR/EGoLVZLEjfvSRo0J8KKSw3ZVXgJNtqzubUAXg+QTmyZ28V1G7BsE4ZYqcp7cTvXKqwpt4PGVIUWWHrwadM27ZRzdtClyJB8U9aHWhTgiF9RtyIyJ6c/eoGf7OkFRAwLm1IFdpfb4lxRX46u/7oXNW44Zc5UH2Qgv4osKUzE2fY7RjuPrMxplNHJfKEg/XPuUlUQYZfRudB3DnuwKn0vyF2IM98L0yyAIsv1seLOiddDMKeslE8MzU/WROxc/ojc42sFFKlSn7jj4hzTbB1eM18r6FpXvGjDFnlehC43VWiPsDgUNHpZDuCJwB9GXX
  template:
    metadata:
      name: guestbook-db-pass
      namespace: default
