---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-first-secret
  namespace: test
spec:
  encryptedData:
    password: AgBLSThw/7IIYWDFTkAAnIpQiigiATESTDZAb92hE4YU46YzYiAx5PweKvRTHgI3jVjkoVC50ntUDLxyNe8hbDo8IFULCx/rp5IRgGRYbidNY+bbl+E/n5FnKv3+RMnwcv1uqmD9XnseqjviMP+RhWGZfqx0dqLKghDwVi+6h/Yb4Iiv/U7HzsiThL+I/F3Boe3866iny24fr0lkji3oUuBVz4Y0yQ12eDWNqf3IuuPwwQCS6As8VsxVrjo7bAnRI31CzN6l9MXdorelL+YDtIcxWlYW3RYnaouXlck1mZfW0t7aMQs3ebitndq4BhxHl0BkJ8hnCXxYQai2cO14zAYqaKED5OAM8Xcms4DEGgZQ4rjvpAxP6GnY6d1HhyPLZTc3UUD5rgLYKDvtVkZSa5/xCCjYH3ScI0YgDelt8Y5CHQOUlXi5cDHaSD85n7JFF0UZ+eH6CDLyXBrHq6Xn7BLqBCofR5OPo+36CN4Jo+alDmGl+6rAIZdoJb+65SDPaCYWmvOs1GOxW/fYE+yokDyv5prfDDjCQ0hfIcR/MN06Scmr5yyXuozwfqvK3TOzTwCkMUtlvmX+01+3SJ73Qml2EiV+rjRX95NQexb2jCidF1lbl1Rh/fAfhSB4UVFCAZwtkTx3JzYUjwnVnzdI0YrcMTA5P6Ul/StXDXk3vRFWwcPcYbtqfsR3rC5HWin+mKIXbGcfzNpFeK+r3dMazPlcpgf6
    username: AgC+b2riSSH5NvlGj2HErWGAoiy1aHs/NvzlI8kbSPEVhtNGNiVGz5e8sBcWkOCMuNOMg+xD2hf9yxzFgISQGf0PtfBApIyEg+03M7tpWyy+i0o1UCULkRfBpVNl1mLhUs3mYXoavDduCTLvpVxE000j2x1BYzepvcw2FUzNvAaiXy9NKsDEm3NQOhyXFxLD7J4EqY0eodKZZLS7bPgQojXHZaKtr0HH3N7rFc+RCkyPiup1ud3XRfN+BKfpu3JPZn5C+Dsu1ewLBjswGZAPGlzfQ/qF962KQtKXIFJSu0VSjwzjmJhJsgkGhzGjqpu/sIbDqJzzoEen9WB3o1OHeY6djpdhJ+A1NtcW3Wo/yH10K6/o5KjK8AwQSK3cyG3cDuQ33Bg41w+U6zoYITa9T2SWgRkKWAUZbpv+Vve+0+f1nfpn7zx54liaAy0f5s63MxIxewdK9AbLDmAmvtTaCSKv8EYkms9MsdEIuDvNoAu6qXdJe9oORGuf8WgMuvv5etr1nh4xlyDp9GiR8KycLdBijnBZaRu50U0LBKFvCkbBtBap38IQGs/hIBdIGSmNfOnW5Ide9LDfdPa019Bb4GzqSq5LlV4JRHJ+hNAldA7/HVwXP2Xw/RaF2ppaeZjn13z+BLnmeohOIa7qSM8VhzZvqkpx6FkezNni93prqP/il9zZTsh82Jv0UMgx3NkUBjPN6M6baPv0kg==
  template:
    metadata:
      name: my-first-secret
      namespace: test
    type: Opaque
