---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-first-secret
  namespace: test
spec:
  encryptedData:
    password: AgDDSzRbyAEQ0QF79YYwnDVuXx+CP7Bi5rTwfOMeYHgBc9ZkzyQ+dfbtwyfxo+p384jFqortuSQF6rfsaKp8JjnXzpk2R08cTfFDNjx6RYkJJ7EH1pAU5l+e8KBY2b1Z2pmg3HuWZTYU4ZuBEw+Hc0YIKBAXeSBesa3icmawZQOoFuD6MCPIRE0fSAyKpkBhQsG4LfoIC3Gikl1vRZJ353q+TMUI9jCLXXqIQImk+AtFM4DFmbcfOAaLoWWPsJpc2DcyJkIsCPnKN9Fi7rm3QstMtX7ymV8H1wCVhoH86TfPqjse2L/QpOE+MXB0Dlru+AZcgtXwGfG0/ohImDY96E1E8gUEdN5GTcOvsOOqghZyhTI1vbYjA+9tPppHaWO55CYGqZfhwf9GGbOZSSwL4FaiZhZU0V/M9rGPMnuNnxviTEaLGAKvBvNoain5/C50qVu7JZ0Kpm2NYrEZ03Y6TghoABb9hNfErXAifyJOTgwgnK/J8vnG/5WuDeOLW3sDkUsaJ3HdUxwcjvb/30Ee/o8yRGEcnPRMWgMyX3aAMwJ2Z3iADNUNQs3ioyQvPEdUD2nHokEx03NTeZpybwqwe3RH5mrfAVU8wZe3+7QEaAWIVLY3kfR+KnhRZ5AUATz0IaWA+eszEC5fq+sDYyNxR2diR7TMK9eAz1LCa7qZztf1Vmcqx/500KAhuwZFs15ZwbR/bx/ihSB5OKtmpdquTMmHXxHIW7e/yA==
    username: AgCyZVuWxxbkPGpENEeUuy2Mn7EeXXAPon8iFDYHG0C4lm0TzNhUsJ+ZidTLxw+YB9Mk91PWqxVLEPDhTEHhJh0LaARviyOxYMhE7f5YLru2MF/NCZdNi++5mCjjZuchdiHqo3o8S6kc9aLcl0eohFaCnvEq7gcft1EOV7yZ2LXLc1ybu9iKZTx6RO9yHfnJGC1wPubcmk/E3qXycC/1OSEJmpxr5G1Od2P5u+AnrO+AwxAdkYWiUbpdR0I8Kmeb/kKt1+tdxu/sLvBXIi6rFl28XJfBFcgOm458If5yzq5BkeLhNmNCxaQWNfsvcEmnG4Mdmosz2/YH5bu1gQucKK2PZLdDmBohAZ1hmZIl9lzDd+NbRZNu0oAnO68oKtV5sMnZrFnKgDjZCYBjVpKOsZpFe9rf2OV54jXW8rZbwuHsS6nqjm7A6jcCBhpD3tkDE4F/+LRtIh2wA8FrVugKGAAOJqbeQTnHfDbNlrgZn51UkQdzJClJugQ0D/QD4OmqIJZVo2op4hBERXyyKH+h25K2i8wq8JA3V/zfq9IXOJoQftwXh13nB5NctXflZzMchI+Ea5myos+JS1XaK5uP7mR5i0pR/asb/3zYRbs4GHZJe4FhpQh26F5ibQYE1UbuH9vmXt8E7B3JkgXvCo+gAgOt1YRHgBuoAi6lrOY89/ac4tL1qyYPJi8p9xr6+kSsKHlX3g1IPYuItA==
  template:
    metadata:
      name: my-first-secret
      namespace: test
