---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-test-secret
  namespace: test
spec:
  encryptedData:
    password: AgBSV7YTPnfzSy3MKsFWRR5zTvtNCAfFZ1krYd2ceJYJCj9t6NlnbekPA496H+1Bha+gpiiQeDwN3dxTw0T8Yq3LGacs1rpatfeAayhpvoqJlNd3avHnwK7tX2qAUjTUFJ0dwpf1un9y+JFv39t0iek6wSmsZ7Yp4TIgo3DGrk4TiHkBe5J0aTefyQNa4BhcSZRJ3nPQLGNncscsdrnDOfFyXS5FDw5VYEPuKT7KBcVKb9YyMePrkLpz5E2vZG/cCVXD+4wPfHR45mt5D5Oc7/dfaKltu0RaCl7T1gJ/jFNzWklXgPkhLXjQf8WCbJkowmrPN2dgQ0FOsensu0Cdivt+l+oMFTApHXGTwoV/sVfHk6PCpOkWakUmcfIyFpFt9zOxdVnYh2Xp3kg0qLDzVvxcuSgWPpVRSkVPTofu7OWAJtGkmtyHVqX9rEio/oBnfAo9ahSkF5OpuFmvjpbgEQ2rFELkw8mMC4Yc9ITOPLy3tFbdPY9IxrCYTSt9vAcAMyXBHQ6bfJft4GzE5Y3fJhe/Uv9CcCODM1GPsApaiWkz/kP4ujHobkKPt8nYwcp65wrGysa5WY11e+q7JMwfYBOHK7mYmxYBqj2tIsVVRvr7EqoUUEukA7YyfB2CjTWR9m05cote4dS0Xdi7kollJ3T3TfFuvLiZI/k4XeW9y9divOLblLBKVxLJpbhRmGo/Ij55SVuYxg2gMwkY7VQDydphN0d5tdScJw==
    username: AgAXYpprHN5kyLVd7cdDnhh7i6OLcxnoa076TgV+neFBH6U7HQfubDvYGgc7yd7OW0FZGij4oT3xAzWl1wUpgFCvjym0DYLVIW430KK1p3/8OtP8h9JUdH2mIwaxEFn5ZG2b9COH0G11OiZelW7Ntbw+4H9LYsQPfQfPhQFfRELj8eHIInCMknNvLUTL21yOPyIRlWtafO3VjIi4TR9nfqeE2CsMiBl8XLwpXgjO1CmgL2OxqN8wlVWEFd6g2CgbovKoLtN36LNFk69e1KVFlzXrmavPCXS2t/9x406x07AFTb1F6JAs9Cjc//8IDnYBTGL0mHiGpPPTw2TJmGDDBY00M2I/d78tdk1uKKo+7knGqJEHpMlTY++zTLOw0E9jpO6OHWb6lT+rPiCJGGK60KzfNX1B9bRzWesUdCOnWuKw8xBA6eTsfY/uz9dN2NquSC1wixXb7mv3DMELFVjomY0gYDVT9ltgVKenlXvcbVYBovJFjldrusP6ojpfCmKgJTSgR3LwNBUQMfhH0EzE81RtHeVvM/tUhlpj4qtrq7dZUlP0aBiHmo5QkiHXXYPzcdElneLSDDuxuOeLC8B81hYKS8gkEhbpopJ5q7whErOeOYD1NK4pizcjnFy6cuiAw8Vx6zYywVD8442JsxdIr3pkWkyQvwP4ls5H9toBb9cyAfluKpngQfZ796lIhxWdeaAWrTmXGB2BwA==
  template:
    metadata:
      name: my-test-secret
      namespace: test
